### ISSUE TITLE
Re-enable WASM tests

### ISSUE THREAD

**Issue by icidasset** [fission-codes/webnative#429]
WASM tests are currently skipped because of a garbage-collection issue.

**Comment by matheus23** [comment]
The error message specifically is:
```
     Uncaught Error: recursive use of an object detected which would lead to unsafe aliasing in rust
      at imports.wbg.__wbindgen_throw (file:///Users/icid/Work/webnative/node_modules/wnfs/wasm_wnfs.js:1075:15)
      at wasm://wasm/001a560e:wasm-function[643]:0x57ed4
      at wasm://wasm/001a560e:wasm-function[642]:0x57ec9
      at wasm://wasm/001a560e:wasm-function[342]:0x4c706
      at file:///Users/icid/Work/webnative/node_modules/wnfs/wasm_wnfs.js:288:74
      at FinalizationRegistry.cleanupSome (<anonymous>)

```
